name: Vibranium Action
description: A Github Action to transfer OpenAPI specification to Vibranium.
author: Om Avhad
inputs:  
  file_name:    
    description: 'The name of the file of OpenAPI spec (located in the root of the repository).'    
    required: true    
    default: 'openapi.json'
runs:
  using: "docker"
  image: "python:3.9"  # Specify the Python version you need
  entrypoint: ["python", "/action/api_spec.py"]
branding:
  icon: shield
  color: blue